# fly.toml app configuration file generated for anime-api-ri6f4g on 2025-06-16T17:15:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anime-api-ri6f4g'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
